experiment_name: "best_ball_logistic"
start_seed: 0
n_seeds: 5
n_folds: 5
datasets_train: 
  - "data/B-ALL/train"
datasets_valid:
  - "data/B-ALL/test"
dataset_config:
  sample_size: 100000
experiment_config:
  alpha: 0.9
  dd_sample_size: 5000
  max_iter: 100000
  bayesian_dd: True
param_grid:
  lr:
    - 0.0001
  negative_penalty:
    - 1
  architecture:
    - [10,1]
  dd_threshold:
    - 97.5
  alpha:
    - 0.9
