experiment_name: "best_ball_cnn"
n_folds: 5
n_seeds: 100
datasets_train: 
  - "data/B-ALL/train"
datasets_valid:
  - "data/B-ALL/test"
dataset_config:
  sample_size: 100000
experiment_config:
  max_iter: 100000
param_grid:
  lr:
    - 0.001
  architecture:
    - [3,6]
  head_arch:
    - [6,1]
