experiment_name: "best_ball_reg"
n_folds: 5
n_seeds: 5
datasets_train: 
  - "data/B-ALL/train"
datasets_valid:
  - "data/B-ALL/test"
dataset_config:
  sample_size: 100000
experiment_config:
  dd_sample_size: 5000
  max_iter: 100000
  bayesian_dd: True
param_grid:
  lr:
    - 0.0001
  negative_penalty:
    - 100
  architecture:
    - [15,15,1]
