experiment_name: "best_cll_cnn"
n_folds: 5
n_seeds: 100
datasets_train: 
  - "data/CLL/train"
  - "data/CLL/val"
datasets_valid:
  - "data/CLL/test"
  - "data/CLL/test_noprop"
dataset_config:
  sample_size: 27000
experiment_config:
  max_iter: 25000
param_grid:
  lr:
    - 0.001
  architecture:
    - [3,3]
  head_arch:
    - [10,1]
