experiment_name: "tuning_cll_cnn"
n_folds: 5
n_seeds: 1
datasets_train: 
  - "data/CLL/train"
datasets_valid:
  - "data/CLL/val"
dataset_config:
  sample_size: 27000
experiment_config:
  max_iter: 25000
param_grid:
  lr:
    - 0.001
    - 0.0001
    - 0.00001
    - 0.000001
  architecture:
    - [3,3]
    - [6,3]
    - [10,3]
    - [15,3]
    - [3,6]
    - [6,6]
    - [10,6]
    - [15,6]
    - [3,10]
    - [6,10]
    - [10,10]
    - [15,10]
    - [3,15]
    - [6,15]
    - [10,15]
    - [15,15]
  head_arch:
    - [3,1]
    - [6,1]
    - [10,1]
    - [15,1]
