experiment_name: "tuning_ball_logistic"
start_seed: 0
n_seeds: 5
datasets: 
  - "data/B-ALL/train"
dataset_config:
  sample_size: 100000
  train_proportions: 0.8
experiment_config:
  alpha: 0.9
  dd_sample_size: 5000
  max_iter: 100000
  bayesian_dd: True
param_grid:
  lr:
    - 0.001
    - 0.0001
    - 0.00001
    - 0.000001
  negative_penalty:
    - 1
  dd_threshold:
    - 95
    - 97.5
    - 99
    - 99.9
    - 99.995
  architecture:
    - [3,1]
    - [6,1]
    - [10,1]
    - [15,1]
    - [2,1]
    - [3,3,1]
    - [6,6,1]
    - [10,10,1]
    - [15,15,1]
    - [4,2,1]
    - [3,3,3,1]
    - [6,6,6,1]
    - [10,10,10,1]
    - [15,15,15,1]
    - [8,4,2,1]
