experiment_name: "tuning_cll_reg"
n_folds: 5
n_seeds: 1
datasets_train: 
  - "data/CLL/train"
datasets_valid:
  - "data/CLL/val"
dataset_config:
  sample_size: 27000
experiment_config:
  dd_sample_size: 5000
  max_iter: 100000
  bayesian_dd: true
param_grid:
  lr:
    - 0.001
    - 0.0001
    - 0.00001
    - 0.000001
  negative_penalty:
    - 1
    - 5
    - 15
    - 30
  architecture:
    - [3,1]
    - [6,1]
    - [10,1]
    - [15,1]
    - [2,1]
    - [3,3,1]
    - [6,6,1]
    - [10,10,1]
    - [15,15,1]
    - [4,2,1]
    - [3,3,3,1]
    - [6,6,6,1]
    - [10,10,10,1]
    - [15,15,15,1]
    - [8,4,2,1]
